# Generated by Django 4.0 on 2021-12-30 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0004_group_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user_1',
        ),
        migrations.RemoveField(
            model_name='group',
            name='user_2',
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
