# Generated by Django 4.0 on 2021-12-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_remove_group_user_1_remove_group_user_2_group_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type_message',
            field=models.CharField(default='string', max_length=50),
        ),
    ]
