# Generated by Django 4.0 on 2021-12-30 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0009_group_is_news_group_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='is_news',
        ),
        migrations.AddField(
            model_name='group',
            name='notis',
            field=models.ManyToManyField(related_name='noti_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
