# Generated by Django 4.0 on 2021-12-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_remove',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
