# Generated by Django 4.0 on 2021-12-18 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_topic_removed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='removed',
        ),
    ]
