# Generated by Django 4.0 on 2021-12-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_topic_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_remove',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
