# Generated by Django 4.0 on 2021-12-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_tag_is_remove'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_public',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_public',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
